### ISSUE TITLE
Hash values do not match across architectures with different Int sizes

### ISSUE THREAD

**Issue by ddssff** [haskell-unordered-containers/hashable#209] opened 2021-07-17 04:47 UTC
Because the result of `hash` is always `Int`, I can't make a `Hashable` instance that can produce string hashes that match across architectures.   I'd like to do this with ghc (64 bit Ints) and ghcjs (56 bit Ints.)  Anyone know a solution?

**Comment by phadej** [comment] 2021-07-17 07:26
This is by design and documented.

https://github.com/haskell-unordered-containers/hashable/blob/master/src/Data/Hashable/Class.hs#L237-L239

Duplicate of https://github.com/haskell-unordered-containers/hashable/issues/139

**Comment by ddssff** [comment] 2021-07-17 12:07
I'm not so much asking for a change to `Hashable` as wondering if there is an existing Haskell solution to my problem.

**Comment by phadej** [comment] 2021-07-17 23:41
There are libraries for cryptohashes, e.g. https://hackage.haskell.org/package/cryptohash-sha256 or cryptonite. I'm not aware of libs for "fast on some platform" hashlibs (i.e. stable but not-so-fast on non-primary platforms. Although GHCJS is usually slow, if there aren't any shims specifically for it).

Note: `hashable` is the driver for `unordered-containers`, where you shouldn't care about exact hash values. If you do, `hashable` is not a library for you.

**Closed by phadej** 2021-07-17 23:41 UTC
