### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by jasonsychau** [haskell-unordered-containers/hashable#183] opened 2020-02-21 16:02 UTC
On cabal 1.24.0.2,

```
Preprocessing library hashable-1.3.0.0...

Data/Hashable/Class.hs:427:26:
    Constructor ‘J#’ should have 1 argument, but has been given 2
    In the pattern: J# size# byteArray
    In an equation for ‘hashWithSalt’:
        hashWithSalt salt n@(J# size# byteArray)
          | n >= minInt && n <= maxInt
          = hashWithSalt salt (fromInteger n :: Int)
          | otherwise
          = let
              size = I# size#
              numBytes = 4 * abs size
            in
              hashByteArrayWithSalt byteArray 0 numBytes salt `hashWithSalt` size
          where
              minInt = fromIntegral (minBound :: Int)
              maxInt = fromIntegral (maxBound :: Int)
    In the instance declaration for ‘Hashable Integer’
```
Do you have quick answer for this?

**Comment by phadej** [comment] 2020-02-21 16:21
Most likely you use a weird build environment, with some hacks as CPP conditionals go wrong. (Also `cabal` 1.24 is relatively old, so it might be a very old and already fixed bug).

**Comment by jasonsychau** [comment] 2020-02-21 16:24
I am trying to build in haste-cabal. Do you know anything about this?

**Comment by phadej** [comment] 2021-02-16 17:40
I think this is issue with `haste` and `Integer` internals. I'm not able to reproduce this. I'll be happy to review a patch making `hashable` compatible with haste.

**Comment by phadej** [comment] 2024-06-08 15:59
Closing as cannot reproduce

**Closed by phadej** 2024-06-08 15:59 UTC
